# Generated by Django 5.0.7 on 2024-07-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(default='', max_length=50)),
                ('url_modelo_3d', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hex', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personalizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('nombre_personalizacion', models.CharField(default='', max_length=50)),
                ('numero_personalizacion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('fecha_publicacion', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('me_gusta', models.CharField(default='', max_length=50)),
                ('no_me_gusta', models.CharField(default='', max_length=50)),
                ('comentarios', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('primer_nombre', models.CharField(default='', max_length=50)),
                ('segundo_nombre', models.CharField(default='', max_length=50)),
                ('primero_apellido', models.CharField(default='', max_length=50)),
                ('segundo_apellido', models.CharField(default='', max_length=50)),
                ('correo', models.CharField(default='', max_length=50)),
                ('contrasena', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
