# Generated by Django 5.0.7 on 2024-08-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario'), ('like', 'Like'), ('dislike', 'Dislike')], max_length=50),
        ),
    ]
