# Generated by Django 5.0.7 on 2024-08-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
